package com.campus.dao;

import com.campus.config.DbProperties;
import com.campus.logic.DatabaseTimeAdapter;
import com.campus.model.Profesor;
import com.campus.model.Curso; 
import com.campus.model.CursoProfesor; 
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 * Data Access Object (DAO). Responsable de la persistencia de datos (Alta Cohesión).
 * Utiliza inyección de dependencias para obtener la configuración de la BD (Bajo Acoplamiento).
 */
public class Database {

    private final DbProperties properties;
    
    public Database(DbProperties properties) {
        this.properties = properties;
        // Carga el driver de forma dinámica
        try {
            Class.forName(properties.getDriver());
        } catch (ClassNotFoundException e) {
            System.err.println("Error al cargar el driver de la BD: " + properties.getDriver());
            e.printStackTrace();
        }
    }
    
    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(
            properties.getUrl(), 
            properties.getUsername(), 
            properties.getPassword()
        );
    }
    
    // Método auxiliar para ejecutar sentencias DROP TABLE e ignorar errores si no existe
    private void dropTableIfExists(Statement stmt, String tableName) {
        try {
            stmt.executeUpdate("DROP TABLE " + tableName);
            System.out.println("Tabla " + tableName + " eliminada (si existía).");
        } catch (SQLException ignored) {
            // Ignorar el error si la tabla no existe (comportamiento normal al inicializar)
        }
    }

    // --------------------------------------------------------------------------
    // MÉTODOS DE CREACIÓN DE TABLAS DINÁMICA (Para H2, MySQL, Oracle)
    // --------------------------------------------------------------------------
    
    private void createFacultadTable(Connection conn, String motor) throws SQLException {
        String sql;
        String idType = (motor.equals("Oracle")) ? "NUMBER GENERATED BY DEFAULT AS IDENTITY" : "INT AUTO_INCREMENT";
        String stringType = (motor.equals("Oracle")) ? "VARCHAR2(100)" : "VARCHAR(100)";
        
        sql = "CREATE TABLE Facultad ("
            + "id " + idType + " PRIMARY KEY, "
            + "nombre " + stringType + " NOT NULL, "
            + "ubicacion " + stringType
            + ")";
        
        try (Statement stmt = conn.createStatement()) {
            dropTableIfExists(stmt, "Facultad");
            stmt.executeUpdate(sql);
            System.out.println("Tabla Facultad creada.");
        }
    }

    private void createProgramaTable(Connection conn, String motor) throws SQLException {
        String sql;
        String idType = (motor.equals("Oracle")) ? "NUMBER GENERATED BY DEFAULT AS IDENTITY" : "INT AUTO_INCREMENT";
        String stringType = (motor.equals("Oracle")) ? "VARCHAR2(100)" : "VARCHAR(100)";
        
        sql = "CREATE TABLE Programa ("
            + "id " + idType + " PRIMARY KEY, "
            + "nombre " + stringType + " NOT NULL, "
            + "facultadId " + idType + ", "
            + "FOREIGN KEY (facultadId) REFERENCES Facultad(id)"
            + ")";
        
        try (Statement stmt = conn.createStatement()) {
            dropTableIfExists(stmt, "Programa");
            stmt.executeUpdate(sql);
            System.out.println("Tabla Programa creada.");
        }
    }

    private void createCursoTable(Connection conn, String motor) throws SQLException {
        String sql;
        String idType = (motor.equals("Oracle")) ? "NUMBER GENERATED BY DEFAULT AS IDENTITY" : "INT AUTO_INCREMENT";
        String stringType = (motor.equals("Oracle")) ? "VARCHAR2(100)" : "VARCHAR(100)";
        String booleanType = (motor.equals("Oracle")) ? "NUMBER(1)" : "BOOLEAN";
        
        // programId será de tipo VARCHAR en la tabla para mapear con Curso.getPrograma() que devuelve String
        sql = "CREATE TABLE Curso ("
            + "id " + idType + " PRIMARY KEY, "
            + "nombre " + stringType + " NOT NULL, "
            + "programaId " + stringType + ", " // Cambiado a STRING para coincidir con Curso.getPrograma()
            + "activo " + booleanType 
            + ")";
        
        try (Statement stmt = conn.createStatement()) {
            dropTableIfExists(stmt, "Curso");
            stmt.executeUpdate(sql);
            System.out.println("Tabla Curso creada.");
        }
    }
    
    private void createProfesorTable(Connection conn, String motor) throws SQLException {
        String sql;
        String idType = (motor.equals("Oracle")) ? "NUMBER GENERATED BY DEFAULT AS IDENTITY" : "INT AUTO_INCREMENT";
        String stringType = (motor.equals("Oracle")) ? "VARCHAR2(100)" : "VARCHAR(100)";
        
        sql = "CREATE TABLE Profesor ("
            + "id " + idType + " PRIMARY KEY, "
            + "nombres " + stringType + " NOT NULL, "
            + "apellidos " + stringType + " NOT NULL, "
            + "email " + stringType + " UNIQUE, "
            + "tipoContrato " + stringType + "(50)"
            + ")";
        
        try (Statement stmt = conn.createStatement()) {
            dropTableIfExists(stmt, "Profesor");
            stmt.executeUpdate(sql);
            System.out.println("Tabla Profesor creada.");
        }
    }
    
    private void createEstudianteTable(Connection conn, String motor) throws SQLException {
        String sql;
        String idType = (motor.equals("Oracle")) ? "NUMBER GENERATED BY DEFAULT AS IDENTITY" : "INT AUTO_INCREMENT";
        String stringType = (motor.equals("Oracle")) ? "VARCHAR2(100)" : "VARCHAR(100)";
        
        sql = "CREATE TABLE Estudiante ("
            + "id " + idType + " PRIMARY KEY, "
            + "nombres " + stringType + " NOT NULL, "
            + "apellidos " + stringType + " NOT NULL, "
            + "email " + stringType + " UNIQUE, "
            + "codigoEstudiante " + stringType + "(20) UNIQUE"
            + ")";
        
        try (Statement stmt = conn.createStatement()) {
            dropTableIfExists(stmt, "Estudiante");
            stmt.executeUpdate(sql);
            System.out.println("Tabla Estudiante creada.");
        }
    }
    
    private void createCursoProfesorTable(Connection conn, String motor) throws SQLException {
        String sql;
        String idType = (motor.equals("Oracle")) ? "NUMBER" : "INT"; // Para FKs no necesitamos AUTO_INCREMENT
        String stringType = (motor.equals("Oracle")) ? "VARCHAR2(10)" : "VARCHAR(10)";
        
        sql = "CREATE TABLE CursoProfesor ("
            + "cursoId " + idType + ", "
            + "profesorId " + idType + ", "
            + "anio " + idType + "(4), "
            + "semestre " + idType + ", " // Coincide con int en CursoProfesor.java
            + "PRIMARY KEY (cursoId, profesorId, anio, semestre), "
            + "FOREIGN KEY (cursoId) REFERENCES Curso(id), "
            + "FOREIGN KEY (profesorId) REFERENCES Profesor(id)"
            + ")";
        
        try (Statement stmt = conn.createStatement()) {
            dropTableIfExists(stmt, "CursoProfesor");
            stmt.executeUpdate(sql);
            System.out.println("Tabla CursoProfesor creada.");
        }
    }
    
    private void createInscripcionTable(Connection conn, String motor) throws SQLException {
        String sql;
        String idType = (motor.equals("Oracle")) ? "NUMBER" : "INT";
        String dateType = (motor.equals("Oracle")) ? "DATE" : "DATE";
        String decimalType = (motor.equals("Oracle")) ? "NUMBER(3,1)" : "DECIMAL(3,1)";
        
        sql = "CREATE TABLE Inscripcion ("
            + "estudianteId " + idType + ", "
            + "cursoId " + idType + ", "
            + "fechaInscripcion " + dateType + " NOT NULL, "
            + "calificacion " + decimalType + ", "
            + "PRIMARY KEY (estudianteId, cursoId), "
            + "FOREIGN KEY (estudianteId) REFERENCES Estudiante(id), "
            + "FOREIGN KEY (cursoId) REFERENCES Curso(id)"
            + ")";
        
        try (Statement stmt = conn.createStatement()) {
            dropTableIfExists(stmt, "Inscripcion");
            stmt.executeUpdate(sql);
            System.out.println("Tabla Inscripcion creada.");
        }
    }
    
    /**
     * Inicializa todas las tablas de la base de datos según el motor activo.
     */
    public void initializeDatabase() {
        String motor = properties.getDbName();
        System.out.println("Inicializando base de datos para el motor: " + motor);
        
        try (Connection conn = getConnection()) {
            // Es crucial crear las tablas en orden de dependencia (sin FKs primero)
            createFacultadTable(conn, motor);
            createProgramaTable(conn, motor);
            createCursoTable(conn, motor);
            createProfesorTable(conn, motor);
            createEstudianteTable(conn, motor);
            createCursoProfesorTable(conn, motor);
            createInscripcionTable(conn, motor);
            
        } catch (SQLException e) {
            System.err.println("Error FATAL al inicializar la base de datos. Verifique la configuración en application.properties.");
            e.printStackTrace();
        }
    }
    
    // --------------------------------------------------------------------------
    // MÉTODOS CRUD (Experto en Información y Creador)
    // --------------------------------------------------------------------------
    
    // Método para agregar un profesor
    public void addProfesor(Profesor profesor) {
        String sql = "INSERT INTO Profesor (nombres, apellidos, email, tipoContrato) VALUES (?, ?, ?, ?)";
        try (Connection conn = getConnection(); 
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setString(1, profesor.getNombres());
            pstmt.setString(2, profesor.getApellidos());
            pstmt.setString(3, profesor.getEmail());
            pstmt.setString(4, profesor.getTipoContrato());
            
            pstmt.executeUpdate();
            System.out.println("Profesor agregado exitosamente a " + properties.getDbName() + ".");
        } catch (SQLException e) {
            System.err.println("Error al agregar profesor:");
            e.printStackTrace();
        }
    }
    
    // Método para agregar un curso
    public void addCurso(Curso curso) {
        String sql = "INSERT INTO Curso (nombre, programaId, activo) VALUES (?, ?, ?)";
        try (Connection conn = getConnection(); 
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setString(1, curso.getNombre());
            // CORREGIDO: Mapeo de String a String para Curso.getPrograma()
            pstmt.setString(2, curso.getPrograma()); 
            pstmt.setBoolean(3, curso.isActivo());
            
            pstmt.executeUpdate();
            System.out.println("Curso agregado exitosamente a " + properties.getDbName() + ".");
        } catch (SQLException e) {
            System.err.println("Error al agregar curso:");
            e.printStackTrace();
        }
    }
    
    // Método para agregar la asociación CursoProfesor
    public void addCursoProfesor(CursoProfesor cp) {
        String sql = "INSERT INTO CursoProfesor (cursoId, profesorId, anio, semestre) VALUES (?, ?, ?, ?)";
        try (Connection conn = getConnection(); 
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            // CORREGIDO: Uso de getInt() para cursoId y profesorId
            pstmt.setInt(1, cp.getCursoId());
            pstmt.setInt(2, cp.getProfesorId());
            pstmt.setInt(3, cp.getAnio());
            // CORREGIDO: Uso de getInt() para semestre
            pstmt.setInt(4, cp.getSemestre());
            
            pstmt.executeUpdate();
            System.out.println("Asignación CursoProfesor agregada exitosamente a " + properties.getDbName() + ".");
        } catch (SQLException e) {
            System.err.println("Error al agregar CursoProfesor:");
            e.printStackTrace();
        }
    }
    
    // Método para obtener todos los profesores (Creador GRASP)
    public List<Profesor> getProfesores() {
        List<Profesor> profesores = new ArrayList<>();
        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {
            ResultSet rs = stmt.executeQuery("SELECT id, nombres, apellidos, email, tipoContrato FROM Profesor");
            while (rs.next()) {
                Profesor p = new Profesor();
                p.setId(rs.getDouble("id"));
                p.setNombres(rs.getString("nombres"));
                p.setApellidos(rs.getString("apellidos"));
                p.setEmail(rs.getString("email"));
                p.setTipoContrato(rs.getString("tipoContrato"));
                profesores.add(p);
            }
        } catch (SQLException e) {
            System.err.println("Error al obtener profesores:");
            e.printStackTrace();
        }
        return profesores;
    }

    // Método para obtener todos los cursos
    public List<Curso> getCursos() {
        List<Curso> cursos = new ArrayList<>();
        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {
            ResultSet rs = stmt.executeQuery("SELECT id, nombre, programaId, activo FROM Curso");
            while (rs.next()) {
                Curso c = new Curso();
                c.setId(rs.getDouble("id"));
                c.setNombre(rs.getString("nombre"));
                // CORREGIDO: Uso de getString() para setPrograma(String)
                c.setPrograma(rs.getString("programaId")); 
                c.setActivo(rs.getBoolean("activo"));
                cursos.add(c);
            }
        } catch (SQLException e) {
            System.err.println("Error al obtener cursos:");
            e.printStackTrace();
        }
        return cursos;
    }
    
    // Método para obtener todas las asignaciones CursoProfesor
    public List<CursoProfesor> getCursoProfesores() {
        List<CursoProfesor> cursosProfesores = new ArrayList<>();
        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {
            ResultSet rs = stmt.executeQuery("SELECT cursoId, profesorId, anio, semestre FROM CursoProfesor");
            while (rs.next()) {
                CursoProfesor cp = new CursoProfesor();
                // CORREGIDO: Uso de getInt() para cursoId
                cp.setCursoId(rs.getInt("cursoId"));
                // CORREGIDO: Uso de getInt() para profesorId
                cp.setProfesorId(rs.getInt("profesorId"));
                cp.setAnio(rs.getInt("anio"));
                // CORREGIDO: Uso de getInt() para semestre
                cp.setSemestre(rs.getInt("semestre"));
                cursosProfesores.add(cp);
            }
        } catch (SQLException e) {
            System.err.println("Error al obtener asignaciones CursoProfesor:");
            e.printStackTrace();
        }
        return cursosProfesores;
    }
    
    // --------------------------------------------------------------------------
    // Lógica Específica del Adaptador (Bajo Acoplamiento)
    // --------------------------------------------------------------------------
    
    public String getDatabaseServerTime(DatabaseTimeAdapter adapter) {
        try (Connection conn = getConnection()) {
            return adapter.getCurrentServerTime(conn);
        } catch (SQLException e) {
            System.err.println("Error en la conexión para obtener la hora: " + e.getMessage());
            return "Error de conexión";
        }
    }
}
